Функции и рекурсия
AMoskvicheva/KotlinforMe pull request #2
Opened 2023-11-16 07:23 UTC by AMoskvicheva

2023-11-17 12:12 UTC, vrnvorona requested changes

2023-11-17 12:12 UTC, vrnvorona commented on Задание 1-5(функции и рекурсия).kt
> +   println(maxOfTwo(33, 3))
проверь вариант maxOfTwo(50, 50) и скажи что получится)

2023-11-17 12:12 UTC, vrnvorona commented on Задание 1-5(функции и рекурсия).kt
> +fun main () {
зачем несколько мейнов? ну в целом не критично конечно но для запуска ругаться же будет на функции с одинаковым именем

2023-11-17 12:12 UTC, vrnvorona commented on Задание 1-5(функции и рекурсия).kt
поч файл задание 1-5 если это задание 3 🤔 
ну либо нужна папка task3 или что то такое

2023-11-17 12:12 UTC, vrnvorona commented on Задание 1-5(функции и рекурсия).kt
ну и в целом - в рамках клуба не критична, но файлы не принято кириллицей называть. обычно используют CamelCase заглавный, типа Task3 или FunctionsAndRecursion

2023-11-17 12:12 UTC, vrnvorona commented on Задание 1-5(функции и рекурсия).kt
> +    /** честно сказать, второй return я добавила благодаря автоматическим подсказкам и
потому что у тебя ветвление внутри цикла такое что может не выполниться условие и return не будет, а функция с типом : Int обязана возвращать Int всегда. поэтому и ругался

2023-11-17 12:12 UTC, vrnvorona commented on Задание 1-5(функции и рекурсия).kt
> +    for (i in 1..n)
это не рекурсия, ты просто через цикл парсишь сама

2023-11-18 13:18 UTC, AMoskvicheva commented on Задание 1-5(функции и рекурсия).kt
> +   println(maxOfTwo(33, 3))
Вернуло 50
Поняла, не учитываю a=b

2023-11-18 13:53 UTC, AMoskvicheva commented on Задание 1-5(функции и рекурсия).kt
> +    for (i in 1..n)
@vrnvorona а почему подсказки пишут, что рекурсия?)
<img width="621" alt="Снимок экрана 2023-11-18 в 19 52 34" src="https://github.com/AMoskvicheva/KotlinforMe/assets/149317632/37a8512c-f826-4408-a9ff-5eb9d4a2858c">

2023-11-19 15:35 UTC, vrnvorona approved these changes

2023-11-19 15:36 UTC, vrnvorona commented on Задание 1-5(функции и рекурсия).kt
> +    for (i in 1..n)
сам вызов конечно рекурсивный, но логика кода не рекурсивная)
новая версия ок

2023-11-19 15:37 UTC, vrnvorona commented on Задание 1-5(функции и рекурсия).kt
> +   println(maxOfTwo(33, 3))
в целом кстати я только сейчас подумал что равный кейс без разницы > или < т.к. они равны
по сути лишняя проверка

спасибо :)

2023-11-20 05:57 UTC, merged